config_tf:
  base:
    parent_frame_id: world
    transform:
      rotation:
        x: 0
        y: 0
        z: 0
        w: 1
      translation:
        x: -1000
        y: 0
        z: 0
  camera:
    parent_frame_id: world
    transform:
      rotation:
        x: -0.683
        y: -0.683
        z: 0.183
        w: 0.183
      translation:
        x: 700
        y: 0
        z: 700
  tool0_controller:
    parent_frame_id: tool0
    transform:
      rotation:
        x: 0
        y: 0
        z: 0
        w: 1
      translation:
        x: 0
        y: 0
        z: 0
  flange:
    parent_frame_id: tool0_controller
    transform:
      rotation:
        x: 0
        y: 0
        z: 0
        w: 1
      translation:
        x: 0
        y: 0
        z: 0
