config:
  vcam:
    hidden: False
    camera_frame_id: "camera"
    trim_x: 2000
    trim_y: 2000
    trim_far: 2000
    trim_near: 500
    ply: ['sma-lab2','mesh/test{:02d}','camera']
vcam:
  frame: 0
seacher:
  streaming: false
sensors:
  streaming: false

